apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
     nodeSelector:
        kubernetes.io/hostname: master1
     containers:
      - name: nfs-server
        image: registry.clstest.com:5000/library/iop/upas/nfs:1.0
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true


