apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: upas-das-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: das
    spec:
      nodeSelector:
        kubernetes.io/hostname: master1
      containers:
      - name: upas-das
        image: registry.clstest.com:5000/library/iop/upas/das:1.0
        imagePullPolicy: Always
        command: ['/bin/bash', '-c', '$USER_HOME/binary/dboot;tail -f $USER_HOME/binary/*.log']
        ports:
        - name: baseport
          containerPort: 9736